export default defineAppConfig({
  authorCN: '古恩豪',
  authorEN: 'Enhao Gu',
  title: 'gu.log',
  role: '华东师范大学软件工程 · 已保研录取',
  status: '华东师范大学 · 软件工程已保研录取，2027 年入学',
  bio: '喜欢折腾。在 AI Infra 和后端之间反复横跳，也做全栈工程。已保研录取华东师范大学软件工程，2027 年入学。有时候打 XCPC，有时候去旅行。',
  description: '写 LLM、Agent、后端工程，偶尔写比赛、实习和旅行。这里是古恩豪的个人笔记与工程记录。',
  github: 'https://github.com/LiangQianXing',
  url: 'https://liangqianxing.github.io',
  friends: [
    {
      name: '小黄鼠',
      url: 'https://liumengxuan04.github.io/about/',
      avatar: 'https://github.com/liumengxuan04.png',
      desc: '一只爱写代码的小黄鼠',
    },
    {
      name: '陈驰水',
      url: 'https://blog.chencs.online/posts/%E5%85%B3%E4%BA%8E%E6%88%91/',
      avatar: 'https://github.com/chenchishui.png',
      desc: '陈驰水的博客',
    },
    {
      name: '石上三年',
      url: 'https://blog.sssn.tech/?p=175',
      avatar: '/images/friends/sssn.jpg',
      desc: '石上三年',
    },
  ],
  nav: [
    { label: '首页', path: '/blog' },
    { label: '文章', path: '/posts' },
    { label: '标签', path: '/tags' },
    { label: '友链', path: '/friends' },
    { label: '关于', path: '/about' },
    { label: '主页', path: '/' },
  ],
  techStack: [
    { name: 'TypeScript', icon: '⬡' },
    { name: 'Go', icon: '⬡' },
    { name: 'Python', icon: '⬡' },
    { name: 'Vue / Nuxt', icon: '⬡' },
    { name: 'Node.js', icon: '⬡' },
    { name: 'PostgreSQL', icon: '⬡' },
    { name: 'Redis', icon: '⬡' },
    { name: 'Docker', icon: '⬡' },
    { name: 'Kubernetes', icon: '⬡' },
    { name: 'LLM / Agent', icon: '⬡' },
  ],
  experience: [
    {
      company: '美团',
      companyEN: 'Meituan',
      logo: '/logos/meituan.svg',
      role: '暑期开发实习生',
      period: '2026.06 – 至今',
      desc: '参与美团内部平台开发，涉及 LLM 相关工程和后端服务。',
    },
    {
      company: '西湖大学',
      companyEN: 'Westlake University',
      logo: '/logos/westlake.png',
      role: '访问学生',
      period: '2025.12 – 2026.03',
      desc: '自然语言处理实验室。',
    },
  ],
  education: [
    {
      school: '华东师范大学',
      schoolEN: 'East China Normal University',
      logo: '/logos/ecnu.png',
      major: '软件工程',
      period: '2027 – 2030',
      status: '已保研录取，2027 年入学',
    },
  ],
})
