export default defineAppConfig({
  authorCN: '古恩豪',
  authorEN: 'Gu EnHao',
  title: 'gu.log',
  role: '拟保研 · 华东师范大学软件工程',
  status: '拟保研至华东师范大学 · 软件工程（2027–2030）',
  bio: '喜欢折腾。在 AI Infra 和后端之间反复横跳，也做全栈工程。拟保研至华东师范大学软件工程（2027–2030）。有时候打 XCPC，有时候去旅行。',
  description: '写 LLM、Agent、后端工程，偶尔写比赛、实习和旅行。拟保研至华东师范大学软件工程（2027–2030）。',
  github: 'https://github.com/LiangQianXing',
  url: 'https://liangqianxing.github.io',
  friends: [
    {
      name: '小黄鼠',
      url: 'https://liumengxuan04.github.io/',
      avatar: 'https://github.com/liumengxuan04.png',
      desc: '一只爱写代码的小黄鼠',
    },
    {
      name: '陈驰水',
      url: 'https://blog.chencs.online/posts/',
      avatar: 'https://github.com/chenchishui.png',
      desc: '陈驰水的博客',
    },
    {
      name: '石上三年',
      url: 'https://blog.sssn.tech/',
      avatar: '/images/friends/sssn.jpg',
      desc: '石上三年',
    },
  ],
  nav: [
    { label: '首页', path: '/' },
    { label: '文章', path: '/posts' },
    { label: '标签', path: '/tags' },
    { label: '友链', path: '/friends' },
    { label: '关于', path: '/about' },
  ],
  techStack: [
    { name: 'TypeScript', icon: '⬡' },
    { name: 'Go', icon: '⬡' },
    { name: 'Python', icon: '⬡' },
    { name: 'Vue / Nuxt', icon: '⬡' },
    { name: 'Node.js', icon: '⬡' },
    { name: 'PostgreSQL', icon: '⬡' },
    { name: 'Redis', icon: '⬡' },
    { name: 'Docker', icon: '⬡' },
    { name: 'Kubernetes', icon: '⬡' },
    { name: 'LLM / Agent', icon: '⬡' },
  ],
  experience: [
    {
      company: '美团',
      companyEN: 'Meituan',
      logo: '/logos/meituan.svg',
      role: '全栈工程师（实习）',
      period: '2026.05 – 至今',
      desc: '参与美团内部平台全栈开发，涉及 LLM 相关工程和后端服务。',
    },
    {
      company: '西湖大学',
      companyEN: 'Westlake University',
      logo: '/logos/westlake.png',
      role: '访问学生',
      period: '2025.12 – 2026.03',
      desc: '自然语言处理实验室。',
    },
  ],
  education: [
    {
      school: '华东师范大学',
      schoolEN: 'East China Normal University',
      major: '软件工程',
      period: '2027 – 2030（拟）',
      status: '拟保研',
    },
  ],
})
